# Request

# Opciones:
# "image_dir"  -> carga imágenes desde carpeta y calcula embeddings
# "images"     -> carga imágenes recibidas en el request y calcula embeddings
# "scene_<scene_num>"     -> carga imagenes desde carpeta y por escena

string experiment_id
string source_type

sensor_msgs/Image[] crops
bool save_experiment
---
bool success
string message

int32 crop_count
int32 reference_count

# Matriz aplanada row-major:
# similarity_matrix[crop_idx * reference_count + reference_idx]
float32[] similarity_matrix

string[] crop_names
int32[] crop_file_indices