#GenerateReferences.srv

# Request
string prompt
int32 num_images
int32 seed

bool save_generated_images
bool save_reference_bank
string reference_bank_id

---
# Response
bool success
string message

int32 generated_reference_count
string output_dir

bool reference_bank_saved