# Request

# Opciones:
# "pth"        -> carga embeddings desde .pth
# "image_dir"  -> carga imágenes desde carpeta y calcula embeddings
# "images"     -> carga imágenes recibidas en el request y calcula embeddings
string source_type

string experiment_id

sensor_msgs/Image[] images

bool save_experiment

---
bool success
string message

int32 reference_count
int32 embedding_dim

bool experiment_saved