# SegmentImage.srv

# Request
string input_dir # Optional for analitics
string experiment_id
bool save_logs

---
# Response
bool success
string message

sensor_msgs/Image[] masks
sensor_msgs/Image[] crops